version: "3"
services:
    nginx:
        container_name: nginx
        restart: always
        build:
            context: ./srcs/requirements/nginx
        env_file:
            - .env
        ports:
            - "443:443"
        volumes:
            - nginx_data:/etc/nginx/ssl
        networks:
            - my_network
    mariadb:
        container_name: mariadb
        restart: always
        build:
            context: ./srcs/requirements/mariadb
        ports:
            - "3306:3306"
        volumes:
            - mariadb_data:/var/lib/mysql
        env_file:
            - .env
        networks:
            - my_network

networks:
    my_network:


volumes:
    mariadb_data:
        driver_opts:
            type: none
            o: bind
            device: /Users/ael-mouz/Desktop/inception/data/mariadb
    nginx_data:
        driver_opts:
            type: none
            o: bind
            device: /Users/ael-mouz/Desktop/inception/data/nginx
    # wordpress-data:
    #     driver: 
    #         - local
    #     driver_opts:
    #         type: 
    #             - 'none'
    #         o: 
    #             - 'bind'
    #         device: 
    #             - '~/data/wordpress'


    #     depends_on:
    #         - wordpress

    # wordpress:
    #     build:
    #         - ./srcs/requirements/wordpress
    #     volumes:
    #         - wordpress-db:/var/www/html
    #     networks:
    #         - my_network
