version: "3"

services:
    mariadb:
        image : mariadb
        container_name: mariadb
        restart: always
        build:
            context: ./srcs/requirements/mariadb
        # ports:
        #     - "3306:3306"
        volumes:
            - mariadb_data:/var/lib/mysql
        env_file:
            - .env
        networks:
            - my_network

    wordpress:
        image : wordpress
        container_name: wordpress
        restart: always
        build:
            context: ./srcs/requirements/wordpress
        # ports:
        #     - "9000:9000"
        volumes:
            - wordpress_data:/var/www/html
        env_file:
            - .env
        networks:
            - my_network
        depends_on:
            - mariadb
            - redis

    nginx:
        image : nginx
        container_name: nginx
        restart: always
        build:
            context: ./srcs/requirements/nginx
        ports:
            - "443:443"
        volumes:
            - wordpress_data:/var/www/html
        env_file:
            - .env
        networks:
            - my_network
        depends_on:
            - wordpress

    adminer:
        image : adminer
        container_name: adminer
        restart: always
        build:
            context: ./srcs/requirements/bonus/adminer
        ports:
            - "8080:8080"
        networks:
            - my_network

    redis:
        image : redis
        container_name: redis
        restart: always
        build:
            context: ./srcs/requirements/bonus/redis
        ports:
            - "6379:6379"
        networks:
            - my_network

    website:
        image : website
        container_name: website
        restart: always
        build:
            context: ./srcs/requirements/bonus/website
        ports:
            - "80:80"
        networks:
            - my_network

    portainer:
        image: portainer
        container_name: portainer
        restart: always
        build:
            context: ./srcs/requirements/bonus/portainer
        ports:
          - "9009:9000"
        volumes:
            - portainer_data:/var/lib/portainer
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - my_network

networks:
    my_network:
        name: Docker network


volumes:
    mariadb_data:
        name: DB
        driver_opts:
            type: none
            o: bind
            device: /Users/ael-mouz/Desktop/inception/data/DB
    wordpress_data:
        name: wordpress
        driver_opts:
            type: none
            o: bind
            device: /Users/ael-mouz/Desktop/inception/data/wordpress
    portainer_data:
        name: portainer
        driver_opts:
            type: none
            o: bind
            device: /Users/ael-mouz/Desktop/inception/data/portainer