version: "3"

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    env_file: .env
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception

  wordpress:
    image: wordpress
    container_name: wordpress
    restart: always
    env_file: .env
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    volumes:
      - html_data:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb
      - redis

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    env_file: .env
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    volumes:
      - html_data:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    build:
      context: ./requirements/bonus/adminer
      dockerfile: Dockerfile
    volumes:
      - html_data:/var/www/html
    networks:
      - inception

  redis:
    image: redis
    container_name: redis
    restart: always
    build:
      context: ./requirements/bonus/redis
      dockerfile: Dockerfile
    volumes:
      - html_data:/var/www/html
    networks:
      - inception

  website:
    image: website
    container_name: website
    restart: always
    env_file: .env
    build:
      context: ./requirements/bonus/website
      dockerfile: Dockerfile
    volumes:
      - html_data:/var/www/html
    networks:
      - inception

  portainer:
    image: portainer
    container_name: portainer
    restart: always
    env_file: .env
    build:
      context: ./requirements/bonus/portainer
      dockerfile: Dockerfile
    ports:
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - bonus

  ftp:
    image: ftp
    container_name: ftp
    restart: always
    env_file: .env
    build:
      context: ./requirements/bonus/ftp
      dockerfile: Dockerfile
    ports:
      - "21:21"
      - "20:20"
      - "40000-40005:40000-40005"
    volumes:
      - html_data:/var/www/html
    networks:
      - bonus
    depends_on:
      - wordpress

networks:
  inception:
    driver: bridge
    name: inception
  bonus:
    driver: bridge
    name: bonus

volumes:
  mariadb_data:
    name: DB
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ael-mouz/data/DB
  html_data:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ael-mouz/data/root
