version: "3"

services:
    mariadb:
        container_name: mariadb
        restart: always
        build:
            context: ./srcs/requirements/mariadb
        ports:
            - "3306:3306"
        volumes:
            - mariadb_data:/var/lib/mysql
        env_file:
            - .env
        networks:
            - my_network

    wordpress:
        container_name: wordpress
        restart: always
        build:
            context: ./srcs/requirements/wordpress
        ports:
            - "9000:9000"
        volumes:
            - wordpress_data:/var/www/html
        env_file:
            - .env
        networks:
            - my_network
        depends_on:
            - mariadb

    nginx:
        container_name: nginx
        restart: always
        build:
            context: ./srcs/requirements/nginx
        ports:
            - "443:443"
        volumes:
            - wordpress_data:/var/www/html
        env_file:
            - .env
        networks:
            - my_network
        depends_on:
            - wordpress

networks:
    my_network:


volumes:
    mariadb_data:
        driver_opts:
            type: none
            o: bind
            device: /Users/ael-mouz/Desktop/inception/data/DB
    wordpress_data:
        driver_opts:
            type: none
            o: bind
            device: /Users/ael-mouz/Desktop/inception/data/wordpress
